-- Users (synced from Entra ID on first login)
create table users (
  id uuid primary key default gen_random_uuid(),
  email text unique not null,
  name text not null,
  entra_id text unique not null,
  role text not null default 'staff',
  created_at timestamptz default now()
);

-- A learning module (one per source document)
create table modules (
  id uuid primary key default gen_random_uuid(),
  slug text unique not null,
  title text not null,
  description text,
  source_filename text not null,
  source_hash text,
  chunk_count int not null default 0,
  is_active boolean default true,
  updated_at timestamptz default now(),
  created_at timestamptz default now()
);

-- A readable section within a module
create table chunks (
  id uuid primary key default gen_random_uuid(),
  module_id uuid references modules(id) on delete cascade not null,
  chunk_index int not null,
  title text not null,
  content text not null,
  content_hash text,
  is_active boolean default true,
  created_at timestamptz default now(),
  unique(module_id, chunk_index)
);

-- Quiz questions (generated by Claude, approved by admin)
create table questions (
  id uuid primary key default gen_random_uuid(),
  chunk_id uuid references chunks(id) on delete cascade not null,
  question_text text not null,
  question_type text not null default 'mcq',
  options jsonb not null,
  correct_index int not null,
  explanation text,
  status text not null default 'draft',
  created_at timestamptz default now()
);

-- Track which chunks a user has completed
create table progress (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references users(id) not null,
  chunk_id uuid references chunks(id) not null,
  completed_at timestamptz default now(),
  unique(user_id, chunk_id)
);

-- Store each quiz attempt
create table quiz_attempts (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references users(id) not null,
  chunk_id uuid references chunks(id) not null,
  score int not null,
  total int not null,
  answers jsonb not null,
  attempted_at timestamptz default now()
);

-- Indexes for common queries
create index idx_chunks_module on chunks(module_id);
create index idx_questions_chunk on questions(chunk_id);
create index idx_progress_user on progress(user_id);
create index idx_progress_chunk on progress(chunk_id);
create index idx_quiz_attempts_user on quiz_attempts(user_id);
create index idx_quiz_attempts_chunk on quiz_attempts(chunk_id);
